
name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   

jobs:
  unit-tests:

    runs-on: self-hosted

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20 
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies    
      run: npm install
    - name: Run integration tests  
      run: npm test

  security-tests:
    needs: unit-tests
    runs-on: self-hosted

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies    
      run: npm install
    - name: Run integration tests  
      run: npm audit
      
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: security-tests
    runs-on: self-hosted
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true    
